#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=45
#SBATCH --mem=200G
#SBATCH --time=48:00:00
#SBATCH --job-name=aeds_test_500
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=laliotis.2@osu.edu
#SBATCH --output=/fs/scratch/PCON0003/klaliotis/noise-aed/out/aeds_test_500.out.%j
#SBATCH --account=PCON0003

#Set echo
set -x

#Activate Conda Environment
source /users/PCON0003/klaliotis/.conda/envs/
source activate local

#Run programs
cd /fs/scratch/PCON0003/klaliotis/noise-aed/

python3 make_inputs.py
python3 aeds.py
